# Generated by Django 2.1.5 on 2019-01-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
