# Generated by Django 2.1.5 on 2019-01-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(max_length=255, verbose_name='价格'),
        ),
    ]
