# Generated by Django 2.1.5 on 2019-01-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190122_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='content',
            field=models.CharField(max_length=90, verbose_name='货物介绍'),
        ),
    ]
